### ISSUE TITLE
Search Widget

### ISSUE THREAD

**Issue by rufuspollock** [okfn/ckanjs-deprecated#21]
Single javascript file that can be included and then called with signature like:

```
 initialize(config)
 search(query, elementToAttachTo, numResultsToShow)
```

Displays list of dataset summaries in element.

**Comment by aron** [comment]
See #4 for additional information regarding the behaviour of the Search widget.

**Comment by aron** [comment]
As of 59ac21a there's now a rudimentary search widget in the widgets folder of the repository. It can be used to display packages/datasets for a specific query.

``` javascript
var widget = CKAN.Widget.Search.create('#my-widget', 'open street map', {
  results: 10, // Optional number of results to show (defaults to 10)
  endpoint: 'http://test.ckan.net' // Optional endpoint (defaults to http://ckan.net)
});

// Update the query at anytime by calling `.query()`
widget.query('budgets');
```

There is a demo (with not styling) up on the GitHub pages http://okfn.github.com/ckanjs/widgets/search/.

Some point for discussion on moving forward.
- Do we want to provide default styling so users can drop it into their site? I'd say yes but what should it be based on? thedatahub.org defaults?
- Should this be integrated into the Datadeck app? It would require the search form to be re-factored to separate the form from the results.
- The base HTML template could be tidied up to be more semantic.

**Comment by rufuspollock** [comment]
I'd say yes to all 3 points but with css (item 1) lowest on the list.

**Comment by rufuspollock** [comment]
Closing as Item 2 became #24 (now closed). HTML template fixing can be done as we go along (and not obvious what exactly more semantic would involve).
