### ISSUE TITLE
Create an Environment object to hold settings and other global values

### ISSUE THREAD

**Issue by afiore** [okfn/ckanjs-deprecated#9]

**Comment by aron** [comment]
Could you explain this ticket in more depth? Is this essentially refactoring `OKFN.Model.configure()`?

**Comment by aron** [comment]
As of 6cb042f30c7ab5d6a03658b6cb919d0ea2c0cc4c there is now a `CKAN.Client.environment()` method that can be used to get/set keys.

I spent a while trying to enable multiple instances of a client (for connecting to multiple endpoints for example) using a Client constructor and passing around config parameters. However I couldn't find a clean simple way of implementing this without giving each instance it's own copy of the model and view  constructors or manually updating model instances when config parameters  changed.

If anyone has any suggestions for an elegant solution I'd love to hear them as I think it would be really useful to be able to host two clients in the same window. But for now I suggest we use `CKAN.Client.environment()` as a global method for accessing data such as current user, API keys and API endpoints.
